# Generated by Django 3.0.3 on 2020-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('ifsc', models.TextField(blank=True, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetaisl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.TextField(blank=True, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_detaisl',
                'managed': False,
            },
        ),
    ]
